### ISSUE TITLE
How to get data through spi?

### ISSUE THREAD

**Issue by South-River** [Destination-SPACE/bmi085-arduino-library#1]
Hi!
I'm a fresh man in using sensor, and I had tried many libs about bmi088(it seems there's no BMI085 lib), all of them failed in init accel and gyro.

**Comment by DeepSpace00** [comment]
> Hi!
> 
> I'm a fresh man in using sensor, and I had tried many libs about bmi088(it seems there's no BMI085 lib), all of them failed in init accel and gyro.

Hi there. The reason why the BMI085 is not supported in the 088 library is because there are on chip buffers that nearly all of the 088 libraries utilize (FIFO). The 085 does not have these features on the chip which is why those libraries do not work. As for SPI support, that is not something I am currently working on, but may become a feature once I have more time to implement it. I apologize for the inconvenience.
-DS

**Comment by South-River** [comment]
> > Hi!
> > I'm a fresh man in using sensor, and I had tried many libs about bmi088(it seems there's no BMI085 lib), all of them failed in init accel and gyro.
> 
> Hi there. The reason why the BMI085 is not supported in the 088 library is because there are on chip buffers that nearly all of the 088 libraries utilize (FIFO). The 085 does not have these features on the chip which is why those libraries do not work. As for SPI support, that is not something I am currently working on, but may become a feature once I have more time to implement it. I apologize for the inconvenience. -DS

Thanks. 
I just noticed this repo [BoschSensortec](https://github.com/BoschSensortec), but this repo cannot ask questions(ORZ) and no one talks about this repo in Google. It seems quite official, but it looks like not for arduino. 
And I found it finished SPI init, read and write functions in common.c. So if I change it's SPI init, read and write functions and make it suitable for arduino, can I get my bmi085 work?

**Comment by DeepSpace00** [comment]
> > > Hi!
> 
> > > I'm a fresh man in using sensor, and I had tried many libs about bmi088(it seems there's no BMI085 lib), all of them failed in init accel and gyro.
> 
> > 
> 
> > Hi there. The reason why the BMI085 is not supported in the 088 library is because there are on chip buffers that nearly all of the 088 libraries utilize (FIFO). The 085 does not have these features on the chip which is why those libraries do not work. As for SPI support, that is not something I am currently working on, but may become a feature once I have more time to implement it. I apologize for the inconvenience. -DS
> 
> 
> 
> Thanks. 
> 
> I just noticed this repo [BoschSensortec](https://github.com/BoschSensortec), but this repo cannot ask questions(ORZ) and no one talks about this repo in Google. It seems quite official, but it looks like not for arduino. 
> 
> And I found it finished SPI init, read and write functions in common.c. So if I change it's SPI init, read and write functions and make it suitable for arduino, can I get my bmi085 work?

I'm not entirely sure. I would have to sit down and look to see. I'm still new to communicating directly to sensors, specifically using i2c. I just published this repo early since, as you found, there isn't really any other options. I will try to include spi support when i compile this code here to an actual arduino library, but that will be at least a few weeks. I'm sorry I can't be of much help with that. My best advice would be to take a look at the datasheet and try to get the SPI init to work. all of the other code in my example might work with that, but again, i am not certain.
-DS

**Comment by South-River** [comment]
> > > > Hi!
> > 
> > 
> > > > I'm a fresh man in using sensor, and I had tried many libs about bmi088(it seems there's no BMI085 lib), all of them failed in init accel and gyro.
> > 
> > 
> > > 
> > 
> > 
> > > Hi there. The reason why the BMI085 is not supported in the 088 library is because there are on chip buffers that nearly all of the 088 libraries utilize (FIFO). The 085 does not have these features on the chip which is why those libraries do not work. As for SPI support, that is not something I am currently working on, but may become a feature once I have more time to implement it. I apologize for the inconvenience. -DS
> > 
> > 
> > Thanks.
> > I just noticed this repo [BoschSensortec](https://github.com/BoschSensortec), but this repo cannot ask questions(ORZ) and no one talks about this repo in Google. It seems quite official, but it looks like not for arduino.
> > And I found it finished SPI init, read and write functions in common.c. So if I change it's SPI init, read and write functions and make it suitable for arduino, can I get my bmi085 work?
> 
> I'm not entirely sure. I would have to sit down and look to see. I'm still new to communicating directly to sensors, specifically using i2c. I just published this repo early since, as you found, there isn't really any other options. I will try to include spi support when i compile this code here to an actual arduino library, but that will be at least a few weeks. I'm sorry I can't be of much help with that. My best advice would be to take a look at the datasheet and try to get the SPI init to work. all of the other code in my example might work with that, but again, i am not certain. -DS

OK, thank you. I would have a try after exam this week.
