### ISSUE TITLE
I managed to get data!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by South-River** [Destination-SPACE/bmi085-arduino-library#2]
There's two repo maybe you need to have a look.
[bmi088-arduino](https://github.com/bolderflight/bmi088-arduino) and [BMI08x-Sensor-API](https://github.com/BoschSensortec/BMI08x-Sensor-API)
The first repo looks like modified from the second repo, and they get data same way, by directly reading registers. 
So you can have a look on [bmi08x_defs.h](https://github.com/BoschSensortec/BMI08x-Sensor-API/blob/master/bmi08x_defs.h), and change the configs such as ACCEL_CHIP_ID in the second repo's [BMI088.h](https://github.com/bolderflight/bmi088-arduino/blob/main/src/BMI088.h), then you can get data from the sensor. 
But there's more configs need to be changed, such as accel's range(BMI088 and BMI085 have a different range) and I would try to deal with them next week.

**Comment by DeepSpace00** [comment]
That's good. You are more than welcome to fork this repo, add your SPI support, and submit a pull request. It's just not on my priority list right now. As you can see from the other repos in this organization, we mainly do hardware, and made this to support it. Just thought the community would benefit from a stepping stone for the 085.
-DS
